##### Menu   菜单
menu:
  Home: /
  Archives: /archives
  Sitemap: /sitemap.xml    
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets  控件
widgets: 
- category
- tag
- rss
## provide six widgets:category,tag,rss,archive,tagcloud,links.
## modify links in `/layout/_widget/links.ejs`.

#### RSS
rss: atom.xml  ## RSS address.

#### Image  图片相关
imglogo:
  enable: true              ## display image logo true/false.  ## 是否显示网站 logo
  src: img/logo.svg         ## `.svg` and `.png` are recommended,please put image into the theme folder `/pacman/source/img`.  ## 网站图标    
favicon: img/favicon.ico    ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/pacman/source/img`.     
apple_icon: img/pacman.jpg  ## size:114px*114px,please put image into the theme folder `/pacman/source/img`. ## 苹果设备上的图标，背景不要透明
author_img: img/author.jpg  ## author_img: /img/author.jpg ## 网站底部的博主头像
##banner_img: img/banner.jpg   ## 博客顶部的图片
#### Author Avatar Picture
author_img_enable: true  ## display author avatar picture
##dataURI: false
dataURI: false
## if the picture's format is dataURI please set the value to true,otherwise set the value to false.
## convert an image into base 64 data URIs http://websemantics.co.uk/online_tools/image_to_data_uri_convertor/ .
author_img_data: ''
## paste the dataURI in ONE LINE and included it by ''.
## author_img: img/author.jpg ## size:220px*220px.
## if the picture's format is `.png` or `.jpg`  instead of dataURI,you should set the `dataURI` value to false.


### 主题颜色
##theme_color:
##    theme: '#2ca6cb'    ##默认主题颜色为蓝色

#### Font
ShowCustomFont: true  
## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/pacman/source/css`.

#### Toc 目录
toc:  
  article: true   ## show contents in article.    ## 是否在文章中显示目录
  aside: true     ## show contents in aside.     ## 是否在侧边栏显示目录
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

### 友情链接
#links:
#  码农圈: https://coderq.com,一个面向程序员交流分享的新一代社区
#  Jark's Blog: http://wuchong.me
  
#### Fancybox
fancybox: true 
## if you use gallery post or want use fancybox please set the value to true.
## if you want use fancybox in ANY post please copy the file `fancybox.js`.
## in theme folder `/pacman/scripts` to your hexo blog folder `../scritps`.

#### Author information  作者信息
author: 
  google_plus:    ## eg:116338260303228776998 for https://plus.google.com/u/0/116338260303228776998
  intro_line1: "Hello ,I'm Larry Page in Google." ## eg: "Hello ,I'm Larry Page in Google."  ## 网站底部的个人介绍
  intro_line2: "This is my blog,believe it or not. " ## eg: "This is my blog,believe it or not."
  weibo: yangcvo     ## e.g. 436062867 for http://weibo.com/436062867
  twitter: yangaov   ## e.g. yangjiansky for https://twitter.com/yangjiansky
  github: yangcvo    ## e.g. A-limon for https://github.com/A-limon
  facebook: yangcvo  ## e.g. yangjian for https://favebook.com/yangjian
  tsina:      ## e.g. 1664838973  Your weibo ID,It will be used in share button.
  linkedin:   ## e.g. in/jeffweiner08 for https://www.linkedin.com/in/jeffweiner08
  email:  yangcvo@gmail.com ##填写你的email地址
  segmentfault: yangc  

#### Comment  评论
duoshuo: 
  enable: true  ## duoshuo.com 
  short_name:     ## duoshuo short name.

#### Share button ###分享按钮
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display. ###  默认使用主题内建分享
  id:    ## e.g. 1501277 your jiathis ID. 
  tsina: ## e.g. 1664838973 Your weibo id,It will be used in share button.

#### Analytics  #### 网站统计
google_analytics:
  enable: false
  id:   ## e.g. UA-1766729-8 your google analytics ID.
  site:  ## e.g. yangjian.me your google analytics site or set the value as auto.    ## 网站地址.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
 
sitemap:
path: sitemap.xml
 #path 表示 Sitemap 的路径. 默认为 sitemap.xml.

#### Custom Search  #### 自定义搜索
google_cse: 
  enable: false
  cx:  ## e.g. 000561263943549425496:mrzrm0gr4kg your Custom Search ID
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
